on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

name: Check code

jobs:
  build:
    name: Lint code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Lint Dockerfile
        run: docker run --rm -i hadolint/hadolint < Dockerfile
      - name: Lint Markdown
        run: |
          gem install mdl
          mdl README.md
